#ifndef _STM_VERSION_H_
#define _STM_VERSION_H_

#define STM_MAJOR_VERSION 	1
#define STM_MINOR_VERSION 	2
#define STM_MICRO_VERSION 	0
#define STM_REVISION	2026

#define QUOTE_(x)		#x
#define QUOTE(x)		QUOTE_(x)

#define STM_VERSION	QUOTE(STM_MAJOR_VERSION.STM_MINOR_VERSION.STM_MICRO_VERSION (Rev STM_REVISION - 2016/03/14 13:08:09))

#endif
