/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//ConfigMsgDataReader.h
#ifndef _ConfigMsgDATAREADER_H_
#define _ConfigMsgDATAREADER_H_

#include "ConfigMsg.h"	



DDS_DEFINE_DATAREADER(ConfigMsgDataReader, ConfigMsg, ConfigMsgSeq)
DDS_DEFINE_DATAREADER(AppInfoMsgDataReader, AppInfoMsg, AppInfoMsgSeq)

#endif
