/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

#include "ConfigMsgDataWriter.h"



/******************************************
	Define the ConfigMsgDataWriter
 ******************************************/
#define TData			ConfigMsg

#include "TDataWriter.tmp"

#undef TData
/******************************************
	Define the AppInfoMsgDataWriter
 ******************************************/
#define TData			AppInfoMsg

#include "TDataWriter.tmp"

#undef TData
