/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//ConfigMsgDataWriter.h
#ifndef _ConfigMsgDATAWRITER_H_
#define _ConfigMsgDATAWRITER_H_

#include "ConfigMsg.h"



DDS_DEFINE_DATAWRITER(ConfigMsgDataWriter, ConfigMsg)
DDS_DEFINE_DATAWRITER(AppInfoMsgDataWriter, AppInfoMsg)


#endif
