/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

#include "ConfigMsgTypeSupport.h"



/******************************************
	Define the ConfigMsgTypeSupport
 ******************************************/
#define TData				ConfigMsg

#include "TTypeSupport.tmp"

#undef TData
/******************************************
	Define the AppInfoMsgTypeSupport
 ******************************************/
#define TData				AppInfoMsg

#include "TTypeSupport.tmp"

#undef TData
