/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

#include "ConfigMsgDataReader.h"



/******************************************
	Define the ConfigMsgDataReader
 ******************************************/
#define TData			ConfigMsg

#include "TDataReader.tmp"

#undef TData
/******************************************
	Define the AppInfoMsgDataReader
 ******************************************/
#define TData			AppInfoMsg

#include "TDataReader.tmp"

#undef TData
