/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//ConfigMsgTypeSupport.h
#ifndef _ConfigMsgTYPESUPPORT_H_
#define _ConfigMsgTYPESUPPORT_H_

#include "ConfigMsg.h"




DDS_DEFINE_TYPESUPPORT(ConfigMsgTypeSupport, ConfigMsg)
DDS_DEFINE_TYPESUPPORT(AppInfoMsgTypeSupport, AppInfoMsg)

#endif
