/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//LogMsgDataWriter.h
#ifndef _LogMsgDATAWRITER_H_
#define _LogMsgDATAWRITER_H_

#include "LogMsg.h"



DDS_DEFINE_DATAWRITER(LogMsgDataWriter, LogMsg)


#endif
