//LogMsg.h
/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

#ifndef _LogMsg_H_
#define _LogMsg_H_

#include "SDDS_Include.h"

typedef struct LogMsg
{
	DDS_LongLong log_time;
	DDS_Int log_level;
	DDS_Int log_definition;
	DDS_Char log_str[256];
} LogMsg;
SDDS_SEQUENCE_DATA(LogMsgSeq, LogMsg);



SDDS_DECLARE_TYPE_METHOD(LogMsg, LogMsg)



SDDS_BEGIN_MEMBER_INFO(LogMsg)
	SDDS_DEFINE_MEMBER_INFO_PRIMITIVE(log_time, DDS_TK_LONGLONG, DDS_LONG_LONG_SIZE, 1, false, DDS_LongLong)
	SDDS_DEFINE_MEMBER_INFO_PRIMITIVE(log_level, DDS_TK_INT, DDS_INT_SIZE, 1, false, DDS_Int)
	SDDS_DEFINE_MEMBER_INFO_PRIMITIVE(log_definition, DDS_TK_INT, DDS_INT_SIZE, 1, false, DDS_Int)
	SDDS_DEFINE_MEMBER_INFO_PRIMITIVE(log_str, DDS_TK_CHAR, DDS_OCTET_SIZE, 256, false, DDS_Char)
SDDS_END_MEMBER_INFO(LogMsg)




#endif
