/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//LogMsgTypeSupport.h
#ifndef _LogMsgTYPESUPPORT_H_
#define _LogMsgTYPESUPPORT_H_

#include "LogMsg.h"




DDS_DEFINE_TYPESUPPORT(LogMsgTypeSupport, LogMsg)

#endif
