/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

//LogMsgDataReader.h
#ifndef _LogMsgDATAREADER_H_
#define _LogMsgDATAREADER_H_

#include "LogMsg.h"	



DDS_DEFINE_DATAREADER(LogMsgDataReader, LogMsg, LogMsgSeq)

#endif
