/********************************************************************************
 * This file was automatically generated by SmartDDS generator.
 * Version 1.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SmartDDS interface file instead.
 ********************************************************************************/

#include "LogMsgDataReader.h"



/******************************************
	Define the LogMsgDataReader
 ******************************************/
#define TData			LogMsg

#include "TDataReader.tmp"

#undef TData
